### PR TITLE
- WIP Updated to use the new project system in VS2017

### PR DESCRIPTION
**Pull request by mwadams**
- Maintained the existing versions of external packages without updating
- Targetting NetStandard1.3 and NetCore1.1

### CODE REVIEW

**Comment by SabotageAndi** [comment]
The NuGet package information got lost during the migration.

**Comment by SabotageAndi** [comment]
About the appveyor build. The config file is here: https://github.com/SabotageAndi/gherkin/blob/DotNetCore/appveyor.yml
Probably you have to change it to VS2017.

**Comment by mwadams** [comment]
Right! Let me get this working, them!

**Comment by mwadams** [comment]
Ah - yes; you can now produce nuget packages as part of the project config. I'll configure that up, too.

**Pull request merged**
